# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChromeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=16)),
                ('mac', models.CharField(max_length=18)),
                ('vtime', models.CharField(max_length=30)),
                ('lvtime', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=255)),
                ('sitename', models.CharField(max_length=255)),
                ('vcount', models.IntegerField()),
            ],
            options={
                'db_table': 'chrome_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_num', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=16)),
                ('mac', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('userdomain', models.CharField(max_length=30)),
                ('computername', models.CharField(max_length=30)),
                ('ipaddress', models.CharField(max_length=16)),
                ('macaddress', models.CharField(max_length=18)),
                ('creationtime', models.CharField(max_length=20)),
                ('lastaccesstime', models.CharField(max_length=20)),
                ('lastwritetime', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('fullname', models.TextField()),
            ],
            options={
                'db_table': 'file_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hrdb',
            fields=[
                ('empnum', models.AutoField(db_column='EMPnum', primary_key=True, serialize=False)),
                ('empname', models.CharField(db_column='EMPname', max_length=20)),
                ('cname', models.CharField(db_column='Cname', max_length=40)),
                ('ip', models.CharField(db_column='IP', max_length=20)),
                ('mac', models.CharField(db_column='MAC', max_length=17)),
                ('center', models.CharField(max_length=10)),
                ('teamnum', models.IntegerField(db_column='teamNum')),
                ('team', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('datehired', models.DateField()),
            ],
            options={
                'db_table': 'hrdb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjAccessLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('accessmask', models.CharField(max_length=255)),
                ('eventid', models.IntegerField(db_column='eventID')),
                ('cname', models.CharField(db_column='Cname', max_length=40)),
                ('uname', models.CharField(db_column='Uname', max_length=40)),
                ('adate', models.DateField(db_column='Adate')),
                ('atime', models.TimeField(db_column='Atime')),
                ('sid', models.CharField(db_column='SID', max_length=255)),
                ('logonid', models.CharField(db_column='logonID', max_length=30)),
                ('domainname', models.CharField(max_length=255)),
                ('objserver', models.CharField(max_length=255)),
                ('objname', models.CharField(max_length=255)),
                ('psname', models.CharField(db_column='PSname', max_length=255)),
            ],
            options={
                'db_table': 'obj_access_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdate', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
                ('ename', models.CharField(max_length=30)),
                ('e_num', models.IntegerField()),
                ('ip', models.CharField(max_length=16)),
                ('mac', models.CharField(max_length=18)),
                ('site', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('filename', models.FileField(upload_to='documents/')),
                ('reason_num', models.CharField(max_length=10)),
                ('log_num', models.CharField(max_length=10)),
                ('violation', models.CharField(blank=True, max_length=10, null=True)),
                ('severity', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'reason',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReasonMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_num', models.CharField(max_length=10)),
                ('reason_num', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'reason_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UactivReports',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('wdate', models.CharField(db_column='Wdate', max_length=10)),
                ('empnum', models.IntegerField(db_column='EMPnum')),
                ('empname', models.CharField(db_column='EMPname', max_length=20)),
                ('center_team', models.CharField(max_length=20)),
                ('log_table', models.CharField(max_length=20)),
                ('log_id', models.IntegerField(db_column='log_ID')),
                ('ip', models.CharField(db_column='IP', max_length=20)),
                ('mac', models.CharField(db_column='MAC', max_length=17)),
                ('outflow_file', models.CharField(db_column='outflow_File', max_length=255)),
                ('url_link', models.CharField(blank=True, db_column='url_Link', max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=40, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver', models.CharField(blank=True, max_length=50, null=True)),
                ('rf_outflow_file', models.CharField(db_column='rf_outflow_File', max_length=50)),
                ('rf_outflow_file_detail', models.TextField(db_column='rf_outflow_File_detail')),
                ('upfilename', models.FileField(upload_to='documents/')),
                ('violation', models.CharField(blank=True, max_length=10, null=True)),
                ('severity', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'uactiv_reports',
                'managed': False,
            },
        ),
    ]
